### ISSUE TITLE
Strange timeouts?

### ISSUE THREAD

**Issue by itsaphel** [sitano/maelstrom-rust-demo#5]
Hi @sitano - really neat library!

I've been working on the fault-tolerant part of the broadcast problem, for which I'm implementing retries, and I'm running into some issues with the RPC logic.

Snippet:
```
let (ctx, _handler) = Context::new();

// Send message with retries
let runtime0 = runtime.clone();
let runtime1 = runtime.clone();
let handler0 = self.clone();
runtime.spawn(async move {
    runtime0
        .call(ctx, node.clone(), Request::Broadcast { message })
        .then(|result| async move {
            if let Err(err) = result {
                error!("Error sending message {} to {}: {}", message, node, err);
                handler0.add_failed_message(node, message, Some(runtime1)).await;
            }
        })
        .await
});
```
(context: https://github.com/itsaphel/dist-sys/blob/0e951997da089309cb1d1aed9d184c0a23a70d1f/src/bin/broadcast.rs#L182-L199)

I run the workload with no failures injected, so I would not expect to see timeouts. Also, since `Context::new()` has no timeout by default, I would expect the `select!` in `RPCResult.done_with` to not fall through to the `_ = ctx.done() => result = Err(Box::new(Error::Timeout))` case.

However, in my node logs I see lots of:

```
[2024-09-14T12:33:12.834793Z ERROR broadcast] Error sending message 1 to n3: error(0): timeout
```

I'm not sure how timeouts are possible in this case? I presume it's due to a cancel signal being received, rather than a timeout, though I'm also not sure how this is possible.

If I change the code to use `runtime0.rpc()` instead, I don't see the timeout errors. But now I don't see any errors at all, even when using `--nemesis partition` (which I'd expect produces error responses?)

So I suppose my questions are:
1. Is there an issue with the `runtime.call()` code?
2. Is there an issue with error handling when using `runtime.rpc()`?

Or (perhaps more likely!) am I doing something wrong here?

**Comment by sitano** [comment]
Hi @itsaphel ! Looking at your code https://github.com/itsaphel/dist-sys/blob/0e951997da089309cb1d1aed9d184c0a23a70d1f/src/bin/broadcast.rs#L182-L199 it seems to me that as soon as you spawn your coroutines with `runtime.spawn()` the `_handler` object goes out of scope and executes Drop impl. On Drop _handler cancels the tokio::context - see https://docs.rs/tokio-context/latest/tokio_context/. Thus resulting your RPC calls got instantly timed out.

```
                    for node in neighbours {
                        let (ctx, _handler) = Context::with_timeout(Duration::from_millis(100));
                        ...
                        // this line is not-blocking, _handler is destroyed right after this call. ctx got cancelled then.
                        runtime.spawn(async move {....call(ctx, node.clone(), Request::Broadcast { message })...});
                    }
```

**Comment by itsaphel** [comment]
Oh I see! Indeed, keeping the handle in scope (https://github.com/itsaphel/dist-sys/commit/b5e96550df38145d2744ab6254fdd80431c013c4) seemed to fix the problem.

Thanks very much!
